gg_rct_ZombieSpawn1 = nil
gg_rct_zombieSpawn2 = nil
gg_rct_zNorthSpawn1 = nil
gg_rct_zWestSpawn1 = nil
gg_rct_waygateBase = nil
gg_rct_waygateNorth = nil
gg_rct_zNorthWestspawn2 = nil
gg_rct_undead_unit_showcase = nil
gg_rct_zEastCapitalSpawn = nil
gg_rct_southZombieSpawn = nil
gg_rct_southSpawn2 = nil
gg_rct_zspawnSouth3 = nil
gg_rct_zSouthspawn4 = nil
gg_rct_baseGameArea = nil
gg_rct_heroModeArea = nil
gg_snd_QuestNew = nil
gg_snd_QuestCompleted = nil
gg_snd_QuestFailed = nil
gg_snd_NagaTheme = ""
gg_snd_Hint = nil
gg_snd_IllidansTheme = ""
gg_snd_UndeadVictory = ""
gg_snd_Undead3 = ""
gg_snd_H02Footman23 = nil
gg_snd_NightElfX1 = ""
gg_snd_TheHornOfCenarius = nil
gg_snd_SargerasRoar = nil
gg_snd_SargerasLaugh = nil
gg_snd_U08Archimonde19 = nil
gg_snd_HeroicVictory = ""
gg_snd_BloodElfTheme = ""
gg_snd_H06Arthas06 = nil
gg_snd_L01Arthas22 = nil
gg_snd_L04Anubarak24 = nil
function InitGlobals()
end

function InitSounds()
gg_snd_QuestNew = CreateSound("Sound/Interface/QuestNew.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_QuestNew, "QuestNew")
SetSoundDuration(gg_snd_QuestNew, 3750)
SetSoundVolume(gg_snd_QuestNew, 80)
gg_snd_QuestCompleted = CreateSound("Sound/Interface/QuestCompleted.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_QuestCompleted, "QuestCompleted")
SetSoundDuration(gg_snd_QuestCompleted, 5154)
SetSoundVolume(gg_snd_QuestCompleted, 80)
gg_snd_QuestFailed = CreateSound("Sound/Interface/QuestFailed.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_QuestFailed, "QuestFailed")
SetSoundDuration(gg_snd_QuestFailed, 4690)
SetSoundVolume(gg_snd_QuestFailed, 80)
gg_snd_NagaTheme = "NagaTheme"
gg_snd_Hint = CreateSound("Sound/Interface/Hint.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_Hint, "Hint")
SetSoundDuration(gg_snd_Hint, 2005)
SetSoundVolume(gg_snd_Hint, 80)
gg_snd_IllidansTheme = "IllidansTheme"
gg_snd_UndeadVictory = "UndeadVictory"
gg_snd_Undead3 = "Undead3"
gg_snd_H02Footman23 = CreateSound("Sound/Dialogue/HumanCampaign/Human02/H02Footman23.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_H02Footman23, "H02Footman23")
SetSoundDuration(gg_snd_H02Footman23, 3683)
SetSoundVolume(gg_snd_H02Footman23, 120)
gg_snd_NightElfX1 = "NightElfX1"
gg_snd_TheHornOfCenarius = CreateSound("Sound/Ambient/DoodadEffects/TheHornOfCenarius.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_TheHornOfCenarius, "HornOfCenariusSound")
SetSoundDuration(gg_snd_TheHornOfCenarius, 12120)
SetSoundVolume(gg_snd_TheHornOfCenarius, 127)
gg_snd_SargerasRoar = CreateSound("Sound/Ambient/DoodadEffects/SargerasRoar.flac", false, true, true, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_SargerasRoar, "SargerasRoar")
SetSoundDuration(gg_snd_SargerasRoar, 4481)
SetSoundVolume(gg_snd_SargerasRoar, 127)
gg_snd_SargerasLaugh = CreateSound("Sound/Ambient/DoodadEffects/SargerasLaugh.flac", false, true, true, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_SargerasLaugh, "SargerasLaugh")
SetSoundDuration(gg_snd_SargerasLaugh, 3326)
SetSoundVolume(gg_snd_SargerasLaugh, 127)
gg_snd_U08Archimonde19 = CreateSound("Sound/Dialogue/UndeadCampaign/Undead08/U08Archimonde19.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_U08Archimonde19, "U08Archimonde19")
SetSoundDuration(gg_snd_U08Archimonde19, 7575)
SetSoundVolume(gg_snd_U08Archimonde19, 120)
gg_snd_HeroicVictory = "HeroicVictory"
gg_snd_BloodElfTheme = "BloodElfTheme"
gg_snd_H06Arthas06 = CreateSound("Sound/Dialogue/HumanCampaign/Human06/H06Arthas06.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_H06Arthas06, "H06Arthas06")
SetSoundDuration(gg_snd_H06Arthas06, 2115)
SetSoundVolume(gg_snd_H06Arthas06, 120)
gg_snd_L01Arthas22 = CreateSound("Sound/Dialogue/UndeadExpCamp/Undead01x/L01Arthas22.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_L01Arthas22, "L01Arthas22")
SetSoundDuration(gg_snd_L01Arthas22, 8594)
SetSoundVolume(gg_snd_L01Arthas22, 120)
gg_snd_L04Anubarak24 = CreateSound("Sound/Dialogue/UndeadExpCamp/Undead04x/L04Anubarak24.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_L04Anubarak24, "L04Anubarak24")
SetSoundDuration(gg_snd_L04Anubarak24, 6138)
SetSoundVolume(gg_snd_L04Anubarak24, 120)
end

function CreateBuildingsForPlayer0()
local p = Player(0)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("h003"), 17728.0, -29120.0, 270.000, FourCC("h003"))
end

function CreateBuildingsForPlayer18()
local p = Player(18)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("ncop"), -384.0, -8704.0, 270.000, FourCC("ncop"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), -2944.0, -8384.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), -2880.0, -8128.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), 1408.0, -7104.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), -2304.0, -7296.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -576.0, -7552.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), -2048.0, -7168.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), 1216.0, -6848.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -1152.0, -15296.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -320.0, -12224.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), 256.0, -5952.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), 512.0, -6144.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 1024.0, -6976.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -2176.0, -7488.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("ncop"), -1280.0, -19200.0, 270.000, FourCC("ncop"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -1216.0, -18048.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -2560.0, -8000.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), -2816.0, -7872.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("h00F"), 704.0, -6400.0, 270.000, FourCC("h00F"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 512.0, -6528.0, 270.000, FourCC("hgtw"))
end

function CreateUnitsForPlayer18()
local p = Player(18)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 15046.8, -29032.4, 270.000, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), 15464.8, -29032.1, 270.000, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("O003"), 18255.8, -29391.1, 146.404, FourCC("O003"))
u = BlzCreateUnitWithSkin(p, FourCC("N005"), 17544.1, -27031.6, 272.829, FourCC("N005"))
u = BlzCreateUnitWithSkin(p, FourCC("hsor"), 15248.4, -29029.9, 270.000, FourCC("hsor"))
u = BlzCreateUnitWithSkin(p, FourCC("hspt"), 15192.5, -28645.5, 270.000, FourCC("hspt"))
u = BlzCreateUnitWithSkin(p, FourCC("Hpal"), 17133.5, -28817.9, 295.209, FourCC("Hpal"))
u = BlzCreateUnitWithSkin(p, FourCC("Hmkg"), 17312.3, -28772.5, 274.016, FourCC("Hmkg"))
u = BlzCreateUnitWithSkin(p, FourCC("Hblm"), 16968.1, -28911.6, 340.793, FourCC("Hblm"))
u = BlzCreateUnitWithSkin(p, FourCC("hmpr"), 15388.3, -28611.5, 278.038, FourCC("hmpr"))
u = BlzCreateUnitWithSkin(p, FourCC("h00I"), 15464.3, -28824.6, 270.000, FourCC("h00I"))
u = BlzCreateUnitWithSkin(p, FourCC("u000"), 18006.7, -27108.9, 274.985, FourCC("u000"))
u = BlzCreateUnitWithSkin(p, FourCC("u001"), 18349.3, -27115.7, 271.746, FourCC("u001"))
u = BlzCreateUnitWithSkin(p, FourCC("u002"), 19113.7, -27119.6, 265.559, FourCC("u002"))
u = BlzCreateUnitWithSkin(p, FourCC("nzom"), 17334.2, -27362.1, 304.579, FourCC("nzom"))
u = BlzCreateUnitWithSkin(p, FourCC("Harf"), 16715.8, -27949.9, 278.620, FourCC("Harf"))
u = BlzCreateUnitWithSkin(p, FourCC("nsoc"), 18819.9, -27119.5, 277.909, FourCC("nsoc"))
u = BlzCreateUnitWithSkin(p, FourCC("ugar"), 18487.8, -26659.9, 266.435, FourCC("ugar"))
u = BlzCreateUnitWithSkin(p, FourCC("nskm"), 17821.0, -27355.8, 310.252, FourCC("nskm"))
u = BlzCreateUnitWithSkin(p, FourCC("uabo"), 17587.6, -26626.4, 259.833, FourCC("uabo"))
u = BlzCreateUnitWithSkin(p, FourCC("umtw"), 17275.9, -26676.7, 276.191, FourCC("umtw"))
u = BlzCreateUnitWithSkin(p, FourCC("uobs"), 17282.4, -27049.2, 282.638, FourCC("uobs"))
u = BlzCreateUnitWithSkin(p, FourCC("Nalc"), 16850.9, -29127.3, 348.473, FourCC("Nalc"))
u = BlzCreateUnitWithSkin(p, FourCC("Nngs"), 16874.5, -29355.4, 12.658, FourCC("Nngs"))
u = BlzCreateUnitWithSkin(p, FourCC("Nbst"), 17194.6, -29675.8, 44.772, FourCC("Nbst"))
u = BlzCreateUnitWithSkin(p, FourCC("Npbm"), 17442.2, -29725.4, 64.658, FourCC("Npbm"))
u = BlzCreateUnitWithSkin(p, FourCC("Nbrn"), 17684.6, -29734.3, 87.854, FourCC("Nbrn"))
u = BlzCreateUnitWithSkin(p, FourCC("Nfir"), 17889.9, -29740.3, 113.111, FourCC("Nfir"))
u = BlzCreateUnitWithSkin(p, FourCC("Nplh"), 18118.2, -29554.6, 138.404, FourCC("Nplh"))
u = BlzCreateUnitWithSkin(p, FourCC("u004"), 18543.9, -27222.5, 253.898, FourCC("u004"))
u = BlzCreateUnitWithSkin(p, FourCC("u003"), 18088.4, -26600.5, 273.790, FourCC("u003"))
u = BlzCreateUnitWithSkin(p, FourCC("u00D"), 19689.1, -27130.7, 260.420, FourCC("u00D"))
u = BlzCreateUnitWithSkin(p, FourCC("n006"), 14207.3, -29023.2, 270.000, FourCC("n006"))
u = BlzCreateUnitWithSkin(p, FourCC("hmtm"), 14108.9, -28182.7, 279.564, FourCC("hmtm"))
u = BlzCreateUnitWithSkin(p, FourCC("n004"), 15382.2, -28293.1, 270.000, FourCC("n004"))
u = BlzCreateUnitWithSkin(p, FourCC("h009"), 14185.1, -28819.8, 270.000, FourCC("h009"))
u = BlzCreateUnitWithSkin(p, FourCC("h000"), 14473.5, -28816.7, 270.000, FourCC("h000"))
u = BlzCreateUnitWithSkin(p, FourCC("n011"), 14730.9, -28869.5, 293.009, FourCC("n011"))
u = BlzCreateUnitWithSkin(p, FourCC("n000"), 14220.0, -28659.4, 270.000, FourCC("n000"))
u = BlzCreateUnitWithSkin(p, FourCC("nckb"), 15609.8, -28231.3, 270.000, FourCC("nckb"))
u = BlzCreateUnitWithSkin(p, FourCC("nwzr"), 15227.5, -28828.6, 280.670, FourCC("nwzr"))
u = BlzCreateUnitWithSkin(p, FourCC("n002"), 15460.5, -27961.6, 271.781, FourCC("n002"))
SetUnitState(u, UNIT_STATE_MANA, 200)
u = BlzCreateUnitWithSkin(p, FourCC("ugho"), 17485.4, -27512.7, 304.040, FourCC("ugho"))
u = BlzCreateUnitWithSkin(p, FourCC("u00J"), 18796.8, -26685.8, 257.813, FourCC("u00J"))
u = BlzCreateUnitWithSkin(p, FourCC("u00K"), 18027.6, -27369.2, 262.539, FourCC("u00K"))
u = BlzCreateUnitWithSkin(p, FourCC("o005"), 14457.3, -29085.4, 282.207, FourCC("o005"))
u = BlzCreateUnitWithSkin(p, FourCC("n00H"), 14787.2, -29053.1, 247.140, FourCC("n00H"))
u = BlzCreateUnitWithSkin(p, FourCC("nskg"), 17545.5, -27357.1, 255.260, FourCC("nskg"))
end

function CreateNeutralHostileBuildings()
local p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("h00D"), 16843.4, -27936.2, 270.000, FourCC("h00D"))
u = BlzCreateUnitWithSkin(p, FourCC("h00D"), 16574.8, -27962.8, 270.000, FourCC("h00D"))
end

function CreateNeutralHostile()
local p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("nech"), -602.9, -9258.2, 136.949, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -196.1, -9263.2, 136.949, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -679.9, -9212.2, 88.091, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -529.9, -9241.1, 10.734, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -571.4, -9228.9, 17.458, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -172.4, -9064.1, 136.949, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -56.2, -9112.5, 88.091, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -99.4, -9047.0, 10.734, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -140.9, -9034.8, 17.458, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -79.8, -9311.6, 88.091, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -123.0, -9246.1, 10.734, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -164.5, -9233.9, 17.458, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -608.9, -9002.3, 136.949, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -577.4, -8973.0, 17.458, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -535.9, -8985.2, 10.734, FourCC("nech"))
u = BlzCreateUnitWithSkin(p, FourCC("nech"), -492.7, -9050.7, 88.091, FourCC("nech"))
end

function CreateNeutralPassiveBuildings()
local p = Player(PLAYER_NEUTRAL_PASSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("ngol"), -5568.0, -13120.0, 270.000, FourCC("ngol"))
SetResourceAmount(u, 90000)
u = BlzCreateUnitWithSkin(p, FourCC("ntav"), 18368.0, -28800.0, 270.000, FourCC("ntav"))
SetUnitColor(u, ConvertPlayerColor(0))
u = BlzCreateUnitWithSkin(p, FourCC("n001"), -320.0, -7552.0, 270.000, FourCC("n001"))
SetUnitColor(u, ConvertPlayerColor(0))
u = BlzCreateUnitWithSkin(p, FourCC("n00B"), -128.0, -8960.0, 270.000, FourCC("n00B"))
u = BlzCreateUnitWithSkin(p, FourCC("ngme"), -512.0, -8960.0, 270.000, FourCC("ngme"))
u = BlzCreateUnitWithSkin(p, FourCC("n00A"), -320.0, -8960.0, 270.000, FourCC("n00A"))
u = BlzCreateUnitWithSkin(p, FourCC("n00U"), -315.1, -8255.0, 270.000, FourCC("n00U"))
u = BlzCreateUnitWithSkin(p, FourCC("n00J"), -687.9, -8524.9, 270.000, FourCC("n00J"))
u = BlzCreateUnitWithSkin(p, FourCC("n00G"), -564.3, -8259.6, 270.000, FourCC("n00G"))
u = BlzCreateUnitWithSkin(p, FourCC("n00E"), -41.0, -8670.2, 270.000, FourCC("n00E"))
u = BlzCreateUnitWithSkin(p, FourCC("n00Z"), -384.0, -9408.0, 270.000, FourCC("n00Z"))
u = BlzCreateUnitWithSkin(p, FourCC("n00X"), -1584.1, -19264.2, 270.000, FourCC("n00X"))
u = BlzCreateUnitWithSkin(p, FourCC("n00V"), -71.5, -8269.5, 270.000, FourCC("n00V"))
u = BlzCreateUnitWithSkin(p, FourCC("n00W"), -545.3, -7873.9, 270.000, FourCC("n00W"))
u = BlzCreateUnitWithSkin(p, FourCC("n00W"), -1441.3, -18369.9, 270.000, FourCC("n00W"))
u = BlzCreateUnitWithSkin(p, FourCC("n00V"), -1031.5, -18765.5, 270.000, FourCC("n00V"))
u = BlzCreateUnitWithSkin(p, FourCC("n00B"), -1024.0, -19456.0, 270.000, FourCC("n00B"))
u = BlzCreateUnitWithSkin(p, FourCC("ngme"), -1408.0, -19456.0, 270.000, FourCC("ngme"))
u = BlzCreateUnitWithSkin(p, FourCC("n00A"), -1216.0, -19456.0, 270.000, FourCC("n00A"))
u = BlzCreateUnitWithSkin(p, FourCC("n00U"), -1275.1, -18751.0, 270.000, FourCC("n00U"))
u = BlzCreateUnitWithSkin(p, FourCC("n00J"), -1583.9, -19020.9, 270.000, FourCC("n00J"))
u = BlzCreateUnitWithSkin(p, FourCC("n00G"), -1524.3, -18755.6, 270.000, FourCC("n00G"))
u = BlzCreateUnitWithSkin(p, FourCC("n00E"), -937.0, -19166.2, 270.000, FourCC("n00E"))
u = BlzCreateUnitWithSkin(p, FourCC("n00X"), -688.1, -8768.2, 270.000, FourCC("n00X"))
u = BlzCreateUnitWithSkin(p, FourCC("ngol"), -3008.0, -16896.0, 270.000, FourCC("ngol"))
SetResourceAmount(u, 90000)
u = BlzCreateUnitWithSkin(p, FourCC("ngol"), 1472.0, -16768.0, 270.000, FourCC("ngol"))
SetResourceAmount(u, 90000)
u = BlzCreateUnitWithSkin(p, FourCC("ngol"), 3136.0, -12800.0, 270.000, FourCC("ngol"))
SetResourceAmount(u, 90000)
u = BlzCreateUnitWithSkin(p, FourCC("ngol"), -2816.0, -10432.0, 270.000, FourCC("ngol"))
SetResourceAmount(u, 90000)
u = BlzCreateUnitWithSkin(p, FourCC("ngol"), 3264.0, -9408.0, 270.000, FourCC("ngol"))
SetResourceAmount(u, 90000)
end

function CreatePlayerBuildings()
CreateBuildingsForPlayer0()
CreateBuildingsForPlayer18()
end

function CreatePlayerUnits()
CreateUnitsForPlayer18()
end

function CreateAllUnits()
CreateNeutralHostileBuildings()
CreateNeutralPassiveBuildings()
CreatePlayerBuildings()
CreateNeutralHostile()
CreatePlayerUnits()
end

function CreateRegions()
local we

gg_rct_ZombieSpawn1 = Rect(6432.0, 18912.0, 7680.0, 20192.0)
gg_rct_zombieSpawn2 = Rect(-8768.0, 19072.0, -7808.0, 20192.0)
gg_rct_zNorthSpawn1 = Rect(-416.0, 22080.0, 672.0, 23200.0)
gg_rct_zWestSpawn1 = Rect(-14496.0, 3296.0, -13376.0, 4416.0)
gg_rct_waygateBase = Rect(-224.0, -352.0, 224.0, 384.0)
gg_rct_waygateNorth = Rect(-1664.0, 16480.0, -1152.0, 16800.0)
gg_rct_zNorthWestspawn2 = Rect(-5440.0, 15392.0, -3392.0, 16512.0)
gg_rct_undead_unit_showcase = Rect(12448.0, -30528.0, 21184.0, -24832.0)
gg_rct_zEastCapitalSpawn = Rect(8320.0, 4896.0, 9344.0, 6112.0)
gg_rct_southZombieSpawn = Rect(6304.0, -6208.0, 7392.0, -5120.0)
gg_rct_southSpawn2 = Rect(-6496.0, -5248.0, -5152.0, -3808.0)
gg_rct_zspawnSouth3 = Rect(-7520.0, -3680.0, -6144.0, -2272.0)
gg_rct_zSouthspawn4 = Rect(4832.0, -6240.0, 5664.0, -5344.0)
gg_rct_baseGameArea = Rect(-6912.0, -21312.0, 4480.0, -5472.0)
gg_rct_heroModeArea = Rect(14912.0, 1312.0, 22144.0, 13024.0)
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
ForcePlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(0), false)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
ForcePlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(1), false)
SetPlayerController(Player(1), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(2), 2)
ForcePlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(2), false)
SetPlayerController(Player(2), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(3), 3)
ForcePlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(3), false)
SetPlayerController(Player(3), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(4), 4)
ForcePlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(4), false)
SetPlayerController(Player(4), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(5), 5)
ForcePlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(5), false)
SetPlayerController(Player(5), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(9), 6)
ForcePlayerStartLocation(Player(9), 6)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(9), false)
SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(10), 7)
ForcePlayerStartLocation(Player(10), 7)
SetPlayerColor(Player(10), ConvertPlayerColor(10))
SetPlayerRacePreference(Player(10), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(10), false)
SetPlayerController(Player(10), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(11), 8)
ForcePlayerStartLocation(Player(11), 8)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(11), false)
SetPlayerController(Player(11), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(12), 9)
ForcePlayerStartLocation(Player(12), 9)
SetPlayerColor(Player(12), ConvertPlayerColor(12))
SetPlayerRacePreference(Player(12), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(12), false)
SetPlayerController(Player(12), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(13), 10)
ForcePlayerStartLocation(Player(13), 10)
SetPlayerColor(Player(13), ConvertPlayerColor(13))
SetPlayerRacePreference(Player(13), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(13), false)
SetPlayerController(Player(13), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(14), 11)
ForcePlayerStartLocation(Player(14), 11)
SetPlayerColor(Player(14), ConvertPlayerColor(14))
SetPlayerRacePreference(Player(14), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(14), false)
SetPlayerController(Player(14), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(15), 12)
ForcePlayerStartLocation(Player(15), 12)
SetPlayerColor(Player(15), ConvertPlayerColor(15))
SetPlayerRacePreference(Player(15), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(15), false)
SetPlayerController(Player(15), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(16), 13)
ForcePlayerStartLocation(Player(16), 13)
SetPlayerColor(Player(16), ConvertPlayerColor(16))
SetPlayerRacePreference(Player(16), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(16), false)
SetPlayerController(Player(16), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(17), 14)
ForcePlayerStartLocation(Player(17), 14)
SetPlayerColor(Player(17), ConvertPlayerColor(17))
SetPlayerRacePreference(Player(17), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(17), false)
SetPlayerController(Player(17), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(18), 15)
ForcePlayerStartLocation(Player(18), 15)
SetPlayerColor(Player(18), ConvertPlayerColor(18))
SetPlayerRacePreference(Player(18), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(18), false)
SetPlayerController(Player(18), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(19), 16)
ForcePlayerStartLocation(Player(19), 16)
SetPlayerColor(Player(19), ConvertPlayerColor(19))
SetPlayerRacePreference(Player(19), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(19), false)
SetPlayerController(Player(19), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(20), 17)
ForcePlayerStartLocation(Player(20), 17)
SetPlayerColor(Player(20), ConvertPlayerColor(20))
SetPlayerRacePreference(Player(20), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(20), false)
SetPlayerController(Player(20), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(21), 18)
ForcePlayerStartLocation(Player(21), 18)
SetPlayerColor(Player(21), ConvertPlayerColor(21))
SetPlayerRacePreference(Player(21), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(21), false)
SetPlayerController(Player(21), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(22), 19)
ForcePlayerStartLocation(Player(22), 19)
SetPlayerColor(Player(22), ConvertPlayerColor(22))
SetPlayerRacePreference(Player(22), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(22), false)
SetPlayerController(Player(22), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(23), 20)
ForcePlayerStartLocation(Player(23), 20)
SetPlayerColor(Player(23), ConvertPlayerColor(23))
SetPlayerRacePreference(Player(23), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(23), false)
SetPlayerController(Player(23), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(1), 0)
SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(2), 0)
SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(3), 0)
SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(4), 0)
SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(5), 0)
SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(18), 0)
SetPlayerState(Player(18), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(5), true)
SetPlayerTeam(Player(10), 1)
SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(11), 1)
SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(12), 1)
SetPlayerState(Player(12), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(13), 1)
SetPlayerState(Player(13), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(14), 1)
SetPlayerState(Player(14), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(15), 1)
SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(16), 1)
SetPlayerState(Player(16), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(17), 1)
SetPlayerState(Player(17), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(19), 1)
SetPlayerState(Player(19), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(20), 1)
SetPlayerState(Player(20), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(21), 1)
SetPlayerState(Player(21), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(22), 1)
SetPlayerState(Player(22), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(23), 1)
SetPlayerState(Player(23), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(22), true)
SetPlayerTeam(Player(9), 2)
SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
end

function InitAllyPriorities()
SetStartLocPrioCount(0, 5)
SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(0, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(0, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(1, 2)
SetStartLocPrio(1, 0, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 1, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(2, 2)
SetStartLocPrio(2, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 1, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(3, 3)
SetStartLocPrio(3, 0, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 1, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 2, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(4, 2)
SetStartLocPrio(4, 0, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 1, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(5, 4)
SetStartLocPrio(5, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(6, 14)
SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 3, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 5, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 6, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 7, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 8, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 9, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 10, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 11, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 12, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 13, 20, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(6, 12)
SetEnemyStartLocPrio(6, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 1, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 2, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(6, 3, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 4, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 5, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 6, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(6, 7, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 8, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(6, 9, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(6, 10, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(7, 8)
SetStartLocPrio(7, 0, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 1, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 2, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 3, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 4, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 5, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 6, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 7, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(7, 5)
SetEnemyStartLocPrio(7, 0, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 1, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 2, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(7, 3, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(7, 4, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(8, 5)
SetStartLocPrio(8, 0, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(8, 1, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(8, 2, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 3, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 4, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(8, 9)
SetEnemyStartLocPrio(8, 0, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 1, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 2, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 3, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 4, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 5, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 6, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 7, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 8, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(9, 1)
SetStartLocPrio(9, 0, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(10, 7)
SetStartLocPrio(10, 0, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 1, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 2, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 3, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 4, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 5, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 6, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(10, 4)
SetEnemyStartLocPrio(10, 0, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 1, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 2, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 3, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(11, 13)
SetStartLocPrio(11, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 6, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 7, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 8, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 9, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 10, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 11, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(11, 3)
SetEnemyStartLocPrio(11, 0, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(11, 1, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(12, 6)
SetStartLocPrio(12, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 5, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(12, 14)
SetEnemyStartLocPrio(12, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 1, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 2, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 3, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 4, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 5, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 6, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 7, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 8, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 9, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 10, 15, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 11, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 12, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 13, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(13, 21)
SetStartLocPrio(13, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 2, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 3, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 5, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 6, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 7, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 8, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 9, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 10, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 11, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 12, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 13, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 14, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 15, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 16, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 17, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 18, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 19, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(13, 21)
SetEnemyStartLocPrio(13, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 1, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 2, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 3, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 4, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 5, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 6, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 7, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 8, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 9, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 10, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 11, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 12, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 13, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 14, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 15, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 16, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 17, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 18, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 19, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(15, 18)
SetStartLocPrio(15, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 1, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 2, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 3, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 4, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 5, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 6, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 7, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 8, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 9, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 11, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 12, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 13, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 14, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 15, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 16, 20, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(15, 18)
SetEnemyStartLocPrio(15, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 2, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 3, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 4, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 5, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 6, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 7, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 8, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 9, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 10, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 11, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 12, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 13, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 14, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 15, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 16, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(16, 9)
SetStartLocPrio(16, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 6, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 7, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(16, 18)
SetEnemyStartLocPrio(16, 0, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 2, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 4, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 5, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 6, 8, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(16, 7, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 8, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 9, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 10, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 11, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 12, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 13, 15, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(16, 14, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 15, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 16, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(17, 16)
SetStartLocPrio(17, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 1, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 5, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 6, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 7, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 8, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 9, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 10, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 11, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 12, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 13, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 14, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 15, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(17, 10)
SetEnemyStartLocPrio(17, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 1, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 2, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 3, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 4, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 5, 15, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 6, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 7, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 8, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 9, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(18, 12)
SetStartLocPrio(18, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 2, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 3, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 5, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 6, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 7, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 8, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 9, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 10, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(18, 1)
SetEnemyStartLocPrio(18, 0, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(19, 14)
SetStartLocPrio(19, 0, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 1, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 2, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 3, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 4, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 5, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 6, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 7, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 8, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 9, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 10, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 12, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(19, 15)
SetEnemyStartLocPrio(19, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 1, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 2, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 3, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 4, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 5, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 6, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 7, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 8, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 9, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 10, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 11, 15, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 12, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 13, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(20, 14)
SetStartLocPrio(20, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 6, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 7, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 8, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 9, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 10, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 11, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 12, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 13, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(20, 12)
SetEnemyStartLocPrio(20, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 2, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 4, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 5, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 6, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 7, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 8, 15, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 9, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 10, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 11, 19, MAP_LOC_PRIO_LOW)
end

function main()
SetCameraBounds(-29952.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -30208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 29952.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 29696.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -29952.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 29696.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 29952.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -30208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
SetTerrainFogEx(0, 6000.0, 7500.0, 0.500, 0.000, 0.000, 0.000)
NewSoundEnvironment("Default")
SetAmbientDaySound("LordaeronSummerDay")
SetAmbientNightSound("LordaeronSummerNight")
SetMapMusic("Music", true, 0)
InitSounds()
CreateRegions()
CreateAllUnits()
InitBlizzard()
InitGlobals()
end

function config()
SetMapName("TRIGSTR_001")
SetMapDescription("TRIGSTR_003")
SetPlayers(21)
SetTeams(21)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, -9856.0, -2240.0)
DefineStartLocation(1, -2880.0, -16064.0)
DefineStartLocation(2, 1024.0, -15872.0)
DefineStartLocation(3, 2368.0, -12800.0)
DefineStartLocation(4, 2368.0, -9472.0)
DefineStartLocation(5, -2048.0, -11072.0)
DefineStartLocation(6, -5760.0, -12352.0)
DefineStartLocation(7, 2240.0, -16768.0)
DefineStartLocation(8, -3584.0, -10624.0)
DefineStartLocation(9, 3392.0, -10176.0)
DefineStartLocation(10, -2240.0, -17088.0)
DefineStartLocation(11, -3648.0, -17344.0)
DefineStartLocation(12, -5376.0, -13888.0)
DefineStartLocation(13, -4800.0, -13184.0)
DefineStartLocation(14, -3392.0, -9920.0)
DefineStartLocation(15, 7552.0, -14144.0)
DefineStartLocation(16, -3776.0, -16832.0)
DefineStartLocation(17, 3392.0, -8640.0)
DefineStartLocation(18, 2816.0, -10048.0)
DefineStartLocation(19, -6080.0, -13696.0)
DefineStartLocation(20, 2880.0, -8704.0)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

