gg_rct_ZombieSpawn1 = nil
gg_rct_zombieSpawn2 = nil
gg_snd_QuestNew = nil
gg_snd_QuestCompleted = nil
gg_snd_QuestFailed = nil
gg_snd_NagaTheme = ""
gg_snd_Hint = nil
gg_snd_IllidansTheme = ""
gg_snd_UndeadVictory = ""
gg_snd_Undead3 = ""
gg_snd_H02Footman23 = nil
gg_snd_NightElfX1 = ""
function InitGlobals()
end

function InitSounds()
gg_snd_QuestNew = CreateSound("Sound/Interface/QuestNew.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_QuestNew, "QuestNew")
SetSoundDuration(gg_snd_QuestNew, 3750)
SetSoundVolume(gg_snd_QuestNew, 80)
gg_snd_QuestCompleted = CreateSound("Sound/Interface/QuestCompleted.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_QuestCompleted, "QuestCompleted")
SetSoundDuration(gg_snd_QuestCompleted, 5154)
SetSoundVolume(gg_snd_QuestCompleted, 80)
gg_snd_QuestFailed = CreateSound("Sound/Interface/QuestFailed.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_QuestFailed, "QuestFailed")
SetSoundDuration(gg_snd_QuestFailed, 4690)
SetSoundVolume(gg_snd_QuestFailed, 80)
gg_snd_NagaTheme = "NagaTheme"
gg_snd_Hint = CreateSound("Sound/Interface/Hint.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_Hint, "Hint")
SetSoundDuration(gg_snd_Hint, 2005)
SetSoundVolume(gg_snd_Hint, 80)
gg_snd_IllidansTheme = "IllidansTheme"
gg_snd_UndeadVictory = "UndeadVictory"
gg_snd_Undead3 = "Undead3"
gg_snd_H02Footman23 = CreateSound("Sound/Dialogue/HumanCampaign/Human02/H02Footman23.flac", false, false, false, 0, 0, "DefaultEAXON")
SetSoundParamsFromLabel(gg_snd_H02Footman23, "H02Footman23")
SetSoundDuration(gg_snd_H02Footman23, 3645)
SetSoundVolume(gg_snd_H02Footman23, 120)
gg_snd_NightElfX1 = "NightElfX1"
end

function CreateBuildingsForPlayer9()
local p = Player(9)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("hcas"), -512.0, 64.0, 270.000, FourCC("hcas"))
u = BlzCreateUnitWithSkin(p, FourCC("o001"), 832.0, -1088.0, 270.000, FourCC("o001"))
u = BlzCreateUnitWithSkin(p, FourCC("ngme"), 2176.0, -1664.0, 270.000, FourCC("ngme"))
u = BlzCreateUnitWithSkin(p, FourCC("n001"), 1152.0, 1216.0, 270.000, FourCC("n001"))
SetUnitColor(u, ConvertPlayerColor(0))
u = BlzCreateUnitWithSkin(p, FourCC("h002"), 1728.0, 896.0, 270.000, FourCC("h002"))
u = BlzCreateUnitWithSkin(p, FourCC("h002"), 2176.0, 320.0, 270.000, FourCC("h002"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -320.0, 3584.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hbar"), 5056.0, 11264.0, 270.000, FourCC("hbar"))
u = BlzCreateUnitWithSkin(p, FourCC("h002"), -3648.0, 5824.0, 270.000, FourCC("h002"))
u = BlzCreateUnitWithSkin(p, FourCC("hctw"), 4288.0, 11264.0, 270.000, FourCC("hctw"))
u = BlzCreateUnitWithSkin(p, FourCC("hctw"), 5312.0, 11968.0, 270.000, FourCC("hctw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 5056.0, 10432.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), 5696.0, 10944.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -7296.0, 10816.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("hgtw"), -7040.0, 10368.0, 270.000, FourCC("hgtw"))
u = BlzCreateUnitWithSkin(p, FourCC("h002"), -5696.0, 12800.0, 270.000, FourCC("h002"))
u = BlzCreateUnitWithSkin(p, FourCC("hcas"), 5632.0, 9152.0, 270.000, FourCC("hcas"))
u = BlzCreateUnitWithSkin(p, FourCC("hctw"), 5184.0, 9664.0, 270.000, FourCC("hctw"))
u = BlzCreateUnitWithSkin(p, FourCC("hctw"), 6080.0, 9664.0, 270.000, FourCC("hctw"))
u = BlzCreateUnitWithSkin(p, FourCC("hctw"), 5184.0, 8640.0, 270.000, FourCC("hctw"))
u = BlzCreateUnitWithSkin(p, FourCC("hctw"), 6080.0, 8640.0, 270.000, FourCC("hctw"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), 3968.0, 8704.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h002"), 7296.0, 10112.0, 270.000, FourCC("h002"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), 6592.0, 9600.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("h004"), 320.0, -2048.0, 270.000, FourCC("h004"))
u = BlzCreateUnitWithSkin(p, FourCC("hbar"), -64.0, -1280.0, 270.000, FourCC("hbar"))
u = BlzCreateUnitWithSkin(p, FourCC("hbar"), -448.0, -1280.0, 270.000, FourCC("hbar"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), 4672.0, 14336.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -2880.0, 14464.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -2560.0, 11584.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), 1920.0, 11648.0, 270.000, FourCC("h003"))
u = BlzCreateUnitWithSkin(p, FourCC("h002"), 960.0, 5760.0, 270.000, FourCC("h002"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -576.0, 13888.0, 270.000, FourCC("h003"))
end

function CreateUnitsForPlayer9()
local p = Player(9)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -476.2, 3717.6, 49.890, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -105.5, 3662.1, 132.027, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 4627.2, 11317.8, 265.976, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 4741.9, 11432.9, 43.661, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 4909.0, 11546.9, 336.917, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 5109.8, 11605.7, 175.094, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -7113.8, 10564.0, 169.788, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -7190.2, 10687.1, 134.686, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), -7044.0, 10491.5, 92.497, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), 5492.1, 9532.2, 90.000, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), 5783.1, 9517.4, 90.000, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 5387.2, 9766.7, 90.000, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 5566.0, 9737.8, 90.000, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 5707.4, 9764.0, 90.000, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("hfoo"), 5868.5, 9758.8, 90.000, FourCC("hfoo"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 7564.0, 10295.8, 339.337, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h000"), 7147.0, 9982.3, 254.831, FourCC("h000"))
u = BlzCreateUnitWithSkin(p, FourCC("h000"), 7266.9, 9904.0, 229.269, FourCC("h000"))
u = BlzCreateUnitWithSkin(p, FourCC("n003"), 1855.0, 663.6, 326.677, FourCC("n003"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -2090.0, -1039.1, 221.689, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -1832.2, -1312.0, 242.564, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -774.3, 1658.1, 86.431, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), -153.4, 1748.7, 119.846, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), 2744.2, -693.5, 353.232, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("hkni"), 2767.7, -1270.0, 30.268, FourCC("hkni"))
u = BlzCreateUnitWithSkin(p, FourCC("n003"), 1955.7, -25.4, 200.300, FourCC("n003"))
u = BlzCreateUnitWithSkin(p, FourCC("n003"), 1891.7, 35.7, 213.365, FourCC("n003"))
end

function CreateBuildingsForPlayer19()
local p = Player(19)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("o000"), 5056.0, -3200.0, 270.000, FourCC("o000"))
u = BlzCreateUnitWithSkin(p, FourCC("o000"), 3648.0, -11264.0, 270.000, FourCC("o000"))
end

function CreateUnitsForPlayer19()
local p = Player(19)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("nckb"), 5336.5, -2930.4, 112.939, FourCC("nckb"))
u = BlzCreateUnitWithSkin(p, FourCC("nw2w"), 3630.4, -11037.4, 100.422, FourCC("nw2w"))
u = BlzCreateUnitWithSkin(p, FourCC("nchg"), 3774.3, -11025.3, 167.206, FourCC("nchg"))
u = BlzCreateUnitWithSkin(p, FourCC("nchg"), 3430.6, -11047.8, 43.485, FourCC("nchg"))
u = BlzCreateUnitWithSkin(p, FourCC("nckb"), 3268.8, -11140.5, 13.415, FourCC("nckb"))
u = BlzCreateUnitWithSkin(p, FourCC("nckb"), 4680.3, -3139.3, 131.069, FourCC("nckb"))
u = BlzCreateUnitWithSkin(p, FourCC("nchg"), 4804.3, -2973.6, 43.485, FourCC("nchg"))
u = BlzCreateUnitWithSkin(p, FourCC("nchg"), 5133.0, -2894.7, 105.014, FourCC("nchg"))
u = BlzCreateUnitWithSkin(p, FourCC("nw2w"), 4943.2, -2910.7, 100.422, FourCC("nw2w"))
u = BlzCreateUnitWithSkin(p, FourCC("nckb"), 3941.0, -11039.2, 271.030, FourCC("nckb"))
end

function CreateNeutralPassiveBuildings()
local p = Player(PLAYER_NEUTRAL_PASSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("ntav"), -1152.0, 192.0, 270.000, FourCC("ntav"))
SetUnitColor(u, ConvertPlayerColor(0))
end

function CreatePlayerBuildings()
CreateBuildingsForPlayer9()
CreateBuildingsForPlayer19()
end

function CreatePlayerUnits()
CreateUnitsForPlayer9()
CreateUnitsForPlayer19()
end

function CreateAllUnits()
CreateNeutralPassiveBuildings()
CreatePlayerBuildings()
CreatePlayerUnits()
end

function CreateRegions()
local we

gg_rct_ZombieSpawn1 = Rect(1312.0, 12992.0, 2560.0, 14272.0)
gg_rct_zombieSpawn2 = Rect(-3936.0, 12256.0, -2976.0, 13856.0)
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
ForcePlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(0), false)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
ForcePlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(1), false)
SetPlayerController(Player(1), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(2), 2)
ForcePlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(2), false)
SetPlayerController(Player(2), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(3), 3)
ForcePlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(3), false)
SetPlayerController(Player(3), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(4), 4)
ForcePlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(4), false)
SetPlayerController(Player(4), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(5), 5)
ForcePlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(5), false)
SetPlayerController(Player(5), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(6), 6)
ForcePlayerStartLocation(Player(6), 6)
SetPlayerColor(Player(6), ConvertPlayerColor(6))
SetPlayerRacePreference(Player(6), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(6), false)
SetPlayerController(Player(6), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(7), 7)
ForcePlayerStartLocation(Player(7), 7)
SetPlayerColor(Player(7), ConvertPlayerColor(7))
SetPlayerRacePreference(Player(7), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(7), false)
SetPlayerController(Player(7), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(8), 8)
ForcePlayerStartLocation(Player(8), 8)
SetPlayerColor(Player(8), ConvertPlayerColor(8))
SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(8), false)
SetPlayerController(Player(8), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(9), 9)
ForcePlayerStartLocation(Player(9), 9)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(9), false)
SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(10), 10)
ForcePlayerStartLocation(Player(10), 10)
SetPlayerColor(Player(10), ConvertPlayerColor(10))
SetPlayerRacePreference(Player(10), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(10), false)
SetPlayerController(Player(10), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(11), 11)
ForcePlayerStartLocation(Player(11), 11)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(11), false)
SetPlayerController(Player(11), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(12), 12)
ForcePlayerStartLocation(Player(12), 12)
SetPlayerColor(Player(12), ConvertPlayerColor(12))
SetPlayerRacePreference(Player(12), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(12), false)
SetPlayerController(Player(12), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(13), 13)
ForcePlayerStartLocation(Player(13), 13)
SetPlayerColor(Player(13), ConvertPlayerColor(13))
SetPlayerRacePreference(Player(13), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(13), false)
SetPlayerController(Player(13), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(14), 14)
ForcePlayerStartLocation(Player(14), 14)
SetPlayerColor(Player(14), ConvertPlayerColor(14))
SetPlayerRacePreference(Player(14), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(14), false)
SetPlayerController(Player(14), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(15), 15)
ForcePlayerStartLocation(Player(15), 15)
SetPlayerColor(Player(15), ConvertPlayerColor(15))
SetPlayerRacePreference(Player(15), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(15), false)
SetPlayerController(Player(15), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(16), 16)
ForcePlayerStartLocation(Player(16), 16)
SetPlayerColor(Player(16), ConvertPlayerColor(16))
SetPlayerRacePreference(Player(16), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(16), false)
SetPlayerController(Player(16), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(17), 17)
ForcePlayerStartLocation(Player(17), 17)
SetPlayerColor(Player(17), ConvertPlayerColor(17))
SetPlayerRacePreference(Player(17), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(17), false)
SetPlayerController(Player(17), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(18), 18)
ForcePlayerStartLocation(Player(18), 18)
SetPlayerColor(Player(18), ConvertPlayerColor(18))
SetPlayerRacePreference(Player(18), RACE_PREF_HUMAN)
SetPlayerRaceSelectable(Player(18), false)
SetPlayerController(Player(18), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(19), 19)
ForcePlayerStartLocation(Player(19), 19)
SetPlayerColor(Player(19), ConvertPlayerColor(19))
SetPlayerRacePreference(Player(19), RACE_PREF_ORC)
SetPlayerRaceSelectable(Player(19), false)
SetPlayerController(Player(19), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(20), 20)
ForcePlayerStartLocation(Player(20), 20)
SetPlayerColor(Player(20), ConvertPlayerColor(20))
SetPlayerRacePreference(Player(20), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(20), false)
SetPlayerController(Player(20), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(21), 21)
ForcePlayerStartLocation(Player(21), 21)
SetPlayerColor(Player(21), ConvertPlayerColor(21))
SetPlayerRacePreference(Player(21), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(21), false)
SetPlayerController(Player(21), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(22), 22)
ForcePlayerStartLocation(Player(22), 22)
SetPlayerColor(Player(22), ConvertPlayerColor(22))
SetPlayerRacePreference(Player(22), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(22), false)
SetPlayerController(Player(22), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(23), 23)
ForcePlayerStartLocation(Player(23), 23)
SetPlayerColor(Player(23), ConvertPlayerColor(23))
SetPlayerRacePreference(Player(23), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(23), false)
SetPlayerController(Player(23), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(1), 0)
SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(2), 0)
SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(3), 0)
SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(4), 0)
SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(5), 0)
SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(6), 0)
SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(7), 0)
SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(8), 0)
SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(9), 0)
SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
SetPlayerTeam(Player(10), 1)
SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(11), 1)
SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(12), 1)
SetPlayerState(Player(12), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(13), 1)
SetPlayerState(Player(13), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(14), 1)
SetPlayerState(Player(14), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(15), 1)
SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(16), 1)
SetPlayerState(Player(16), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(17), 1)
SetPlayerState(Player(17), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(20), 1)
SetPlayerState(Player(20), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(21), 1)
SetPlayerState(Player(21), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(22), 1)
SetPlayerState(Player(22), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(23), 1)
SetPlayerState(Player(23), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(20), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(22), true)
SetPlayerAllianceStateAllyBJ(Player(21), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(22), Player(23), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(20), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(21), true)
SetPlayerAllianceStateAllyBJ(Player(23), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(20), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(22), true)
SetPlayerAllianceStateVisionBJ(Player(21), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(22), Player(23), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(20), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(21), true)
SetPlayerAllianceStateVisionBJ(Player(23), Player(22), true)
SetPlayerTeam(Player(18), 2)
SetPlayerState(Player(18), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(19), 2)
SetPlayerState(Player(19), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(18), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(18), true)
end

function InitAllyPriorities()
SetStartLocPrioCount(0, 8)
SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(1, 8)
SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(2, 8)
SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(3, 8)
SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(4, 8)
SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(5, 8)
SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(6, 8)
SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(7, 8)
SetStartLocPrio(7, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(8, 8)
SetStartLocPrio(8, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 7, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(9, 16)
SetStartLocPrio(9, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 3, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 5, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 6, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 7, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 8, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 9, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 10, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 11, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 12, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 13, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 14, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 15, 23, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(9, 14)
SetEnemyStartLocPrio(9, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 1, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 2, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 3, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 4, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 5, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 6, 15, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 7, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 8, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 9, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 10, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 11, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 12, 22, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(10, 8)
SetStartLocPrio(10, 0, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 1, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 2, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 3, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 4, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 5, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 6, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 7, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(10, 5)
SetEnemyStartLocPrio(10, 0, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 1, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 2, 20, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 3, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 4, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(11, 5)
SetStartLocPrio(11, 0, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 1, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 2, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 3, 21, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 4, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(11, 9)
SetEnemyStartLocPrio(11, 0, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 1, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 2, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 3, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 4, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 5, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 6, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 7, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 8, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(12, 1)
SetStartLocPrio(12, 0, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(13, 7)
SetStartLocPrio(13, 0, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 1, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 2, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 3, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 4, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 5, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 6, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(13, 6)
SetEnemyStartLocPrio(13, 0, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 1, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 2, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 3, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 4, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 5, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(14, 15)
SetStartLocPrio(14, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 6, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 7, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 8, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 9, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 10, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 11, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 12, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 13, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(14, 3)
SetEnemyStartLocPrio(14, 0, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 1, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(15, 7)
SetStartLocPrio(15, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 6, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(15, 15)
SetEnemyStartLocPrio(15, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 1, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 2, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 3, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 4, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 5, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 6, 8, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 7, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 8, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 9, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 10, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 11, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 12, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 13, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 14, 22, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(16, 24)
SetStartLocPrio(16, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 2, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 3, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 5, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 6, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 7, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 8, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 9, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 10, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 11, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 12, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 13, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 14, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 15, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 16, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 17, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 18, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 19, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 20, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 21, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 22, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(16, 24)
SetEnemyStartLocPrio(16, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 1, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 2, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 3, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 4, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 5, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 6, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 7, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 8, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 9, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 10, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 11, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 12, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 13, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 14, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 15, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 16, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 17, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 18, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 19, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 20, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 21, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 22, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(18, 21)
SetStartLocPrio(18, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 1, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 2, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 3, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 4, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 5, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 6, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 7, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 8, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 9, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 11, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 12, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 13, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 14, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 15, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 16, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrio(18, 17, 21, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 18, 22, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 19, 23, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(18, 21)
SetEnemyStartLocPrio(18, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 2, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 3, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 4, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 5, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 6, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 7, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 8, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 9, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 10, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 11, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 12, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 13, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 14, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 15, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 16, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 17, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 18, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(18, 19, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(19, 12)
SetStartLocPrio(19, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 7, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 9, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 10, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(19, 21)
SetEnemyStartLocPrio(19, 0, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 2, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 4, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 5, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 6, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 7, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 8, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 9, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 10, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 11, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 12, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 13, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 14, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 15, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 16, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 17, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 18, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 19, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(20, 19)
SetStartLocPrio(20, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 1, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 8, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 9, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 11, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 12, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 13, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 14, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 15, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 16, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 17, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(20, 18, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(20, 12)
SetEnemyStartLocPrio(20, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 1, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 2, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 3, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 4, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 5, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 6, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 7, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 8, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 9, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 10, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 11, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(21, 14)
SetStartLocPrio(21, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 2, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 3, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 5, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 6, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 7, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 8, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 9, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 10, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 11, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 12, 20, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(21, 1)
SetEnemyStartLocPrio(21, 0, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(22, 16)
SetStartLocPrio(22, 0, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 1, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 2, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 3, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 4, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(22, 5, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 6, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 7, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 8, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 9, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 10, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 11, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 12, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 13, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(22, 14, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(22, 16)
SetEnemyStartLocPrio(22, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 1, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 2, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 3, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(22, 4, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 5, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(22, 6, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 7, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 8, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(22, 9, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 10, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(22, 11, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(22, 12, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 13, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 14, 21, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(23, 16)
SetStartLocPrio(23, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 6, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 7, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 8, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 9, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 10, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 11, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 12, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 13, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 14, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 15, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(23, 14)
SetEnemyStartLocPrio(23, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 2, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 4, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 5, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 6, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 7, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 8, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 9, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 10, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 11, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 12, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 13, 22, MAP_LOC_PRIO_LOW)
end

function main()
SetCameraBounds(-29952.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -30208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 29952.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 29696.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -29952.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 29696.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 29952.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -30208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
NewSoundEnvironment("Default")
SetAmbientDaySound("LordaeronSummerDay")
SetAmbientNightSound("LordaeronSummerNight")
SetMapMusic("Music", true, 0)
InitSounds()
CreateRegions()
CreateAllUnits()
InitBlizzard()
InitGlobals()
end

function config()
SetMapName("TRIGSTR_001")
SetMapDescription("TRIGSTR_003")
SetPlayers(24)
SetTeams(24)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, -512.0, 0.0)
DefineStartLocation(1, -512.0, 0.0)
DefineStartLocation(2, -512.0, 0.0)
DefineStartLocation(3, -512.0, 0.0)
DefineStartLocation(4, -512.0, 0.0)
DefineStartLocation(5, -512.0, 0.0)
DefineStartLocation(6, -512.0, 0.0)
DefineStartLocation(7, -512.0, 0.0)
DefineStartLocation(8, -512.0, 0.0)
DefineStartLocation(9, -512.0, 0.0)
DefineStartLocation(10, -4736.0, -128.0)
DefineStartLocation(11, -17984.0, -16960.0)
DefineStartLocation(12, -960.0, 4544.0)
DefineStartLocation(13, -128.0, -4672.0)
DefineStartLocation(14, 13632.0, -1792.0)
DefineStartLocation(15, 3776.0, 8000.0)
DefineStartLocation(16, 5632.0, -1280.0)
DefineStartLocation(17, -14080.0, 2816.0)
DefineStartLocation(18, -5248.0, 3520.0)
DefineStartLocation(19, 1600.0, 6848.0)
DefineStartLocation(20, -9152.0, 27008.0)
DefineStartLocation(21, -6148.3, -7775.5)
DefineStartLocation(22, -3501.7, 2840.5)
DefineStartLocation(23, 4333.2, -2636.4)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

